version: "3"
services:
    react-app:
        build: ./live_better
        image: react-app
        container_name:  react-app
        stdin_open: true
        ports:
            - "3000:3000"
        networks:
            - live-better-app
        volumes:
            - './live_better:/usr/src/app'
            - '/usr/src/app/node_modules'
        environment: 
            - CHOKIDAR_USEPOLLING=true
        depends_on: 
            - api-server
    api-server:
        build: ./backend
        image: api-server
        container_name: api-server
        ports:
            - "3001:3001"
        networks:
            - live-better-app
        volumes:
            - './backend:/usr/src/app'
            - '/usr/src/app/node_modules'  
networks:
    live-better-app:
        driver: bridge